# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NetworkExperiment' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NetworkExperiment
  pod 'WikipediaFetcher', :path => './modules/WikipediaFetcher'
  pod 'Fetcher', :path => './modules/Fetcher'
end
